// 示例数据 - 用于初始化
export const sampleMembers = [
  {
    id: 'grandfather-1',
    name: '张大山',
    nickname: '大山',
    gender: 'male' as const,
    birthday: '1950-03-15',
    workplace: '北京',
    bio: '家族长辈，退休教师',
    photo: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'grandmother-1',
    name: '李秀英',
    nickname: '秀英',
    gender: 'female' as const,
    birthday: '1952-08-20',
    workplace: '北京',
    bio: '家族长辈，退休医生',
    photo: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'father-1',
    name: '张伟',
    nickname: '伟伟',
    gender: 'male' as const,
    birthday: '1975-06-10',
    workplace: '上海',
    bio: '家族长子，工程师',
    photo: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mother-1',
    name: '王丽',
    nickname: '丽丽',
    gender: 'female' as const,
    birthday: '1978-11-25',
    workplace: '上海',
    bio: '张伟的妻子，教师',
    photo: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'uncle-1',
    name: '张强',
    nickname: '强强',
    gender: 'male' as const,
    birthday: '1980-09-05',
    workplace: '广州',
    bio: '家族次子，医生',
    photo: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'aunt-1',
    name: '张芳',
    nickname: '芳芳',
    gender: 'female' as const,
    birthday: '1983-04-18',
    workplace: '深圳',
    bio: '家族女儿，设计师',
    photo: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'child-1',
    name: '张明',
    nickname: '小明',
    gender: 'male' as const,
    birthday: '2000-01-15',
    workplace: '杭州',
    bio: '张伟的长子，程序员',
    photo: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'child-2',
    name: '张婷',
    nickname: '婷婷',
    gender: 'female' as const,
    birthday: '2003-07-08',
    workplace: '北京',
    bio: '张伟的女儿，大学生',
    photo: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const sampleRelations = [
  // 祖父母的婚姻关系
  {
    id: 'rel-1',
    sourceId: 'grandfather-1',
    targetId: 'grandmother-1',
    type: 'spouse' as const,
    subType: 'husband-wife' as const,
    createdAt: new Date().toISOString(),
  },
  // 祖父母与父亲的血缘关系
  {
    id: 'rel-2',
    sourceId: 'grandfather-1',
    targetId: 'father-1',
    type: 'parent-child' as const,
    subType: 'father-son' as const,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'rel-3',
    sourceId: 'grandmother-1',
    targetId: 'father-1',
    type: 'parent-child' as const,
    subType: 'mother-son' as const,
    createdAt: new Date().toISOString(),
  },
  // 祖父母与张强的血缘关系
  {
    id: 'rel-4',
    sourceId: 'grandfather-1',
    targetId: 'uncle-1',
    type: 'parent-child' as const,
    subType: 'father-son' as const,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'rel-5',
    sourceId: 'grandmother-1',
    targetId: 'uncle-1',
    type: 'parent-child' as const,
    subType: 'mother-son' as const,
    createdAt: new Date().toISOString(),
  },
  // 祖父母与张芳的血缘关系
  {
    id: 'rel-6',
    sourceId: 'grandfather-1',
    targetId: 'aunt-1',
    type: 'parent-child' as const,
    subType: 'father-daughter' as const,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'rel-7',
    sourceId: 'grandmother-1',
    targetId: 'aunt-1',
    type: 'parent-child' as const,
    subType: 'mother-daughter' as const,
    createdAt: new Date().toISOString(),
  },
  // 张伟和王丽的婚姻关系
  {
    id: 'rel-8',
    sourceId: 'father-1',
    targetId: 'mother-1',
    type: 'spouse' as const,
    subType: 'husband-wife' as const,
    createdAt: new Date().toISOString(),
  },
  // 张伟、王丽与孩子的血缘关系
  {
    id: 'rel-9',
    sourceId: 'father-1',
    targetId: 'child-1',
    type: 'parent-child' as const,
    subType: 'father-son' as const,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'rel-10',
    sourceId: 'mother-1',
    targetId: 'child-1',
    type: 'parent-child' as const,
    subType: 'mother-son' as const,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'rel-11',
    sourceId: 'father-1',
    targetId: 'child-2',
    type: 'parent-child' as const,
    subType: 'father-daughter' as const,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'rel-12',
    sourceId: 'mother-1',
    targetId: 'child-2',
    type: 'parent-child' as const,
    subType: 'mother-daughter' as const,
    createdAt: new Date().toISOString(),
  },
  // 兄弟姐妹关系
  {
    id: 'rel-13',
    sourceId: 'father-1',
    targetId: 'uncle-1',
    type: 'sibling' as const,
    subType: 'brother-brother' as const,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'rel-14',
    sourceId: 'father-1',
    targetId: 'aunt-1',
    type: 'sibling' as const,
    subType: 'brother-sister' as const,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'rel-15',
    sourceId: 'uncle-1',
    targetId: 'aunt-1',
    type: 'sibling' as const,
    subType: 'brother-sister' as const,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'rel-16',
    sourceId: 'child-1',
    targetId: 'child-2',
    type: 'sibling' as const,
    subType: 'brother-sister' as const,
    createdAt: new Date().toISOString(),
  },
];
